import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import LowerNavbar from '@/components/LowerNavbar'
import Footer from '@/components/Footer'
import LowerFooter from '@/components/LowerFooter'
import './globals.css'
import { CartProvider } from '@/context/CartContext'

const inter = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} antialiased bg-slate-50`}>
        <section className="bg-white">
          <div className="max-w-7xl mx-auto px-6">
            <Navbar />
            <LowerNavbar />
          </div>
        </section>
        <main className="max-w-7xl mx-auto px-6 ">
          <CartProvider>{children}</CartProvider>
        </main>

        <section className="bg-white  w-full">
          <div className="max-w-7xl mx-auto ">
            <Footer />
          </div>
        </section>
        <section className="bg-gray-secondary w-full">
          <div className="max-w-7xl mx-auto">
            <LowerFooter />
          </div>
        </section>
      </body>
    </html>
  )
}
